import type { Driver } from "@/types/driver";
import type { Tour, Booking, TourEarning, PayoutSummary } from "@/types/tour";

export const mockDriver: Driver = {
  id: "drv_001",
  name: "Ramesh Gupta",
  rating: 4.9,
  totalTrips: 312,
  bio: "Passionate local guide with 8 years of experience showing visitors the hidden gems of Agra and Mathura. Fluent in Hindi, English, and basic Japanese.",
  languages: ["Hindi", "English", "Japanese (basic)"],
  yearsExperience: 8,
  specialties: ["heritage", "religious", "city"],
  totalToursRun: 312,
  totalGuestsHosted: 1847,
  licenseNumber: "UP-2016-0034521",
  isVerified: true,
  gender: "",
  aadharNumber: "",
  aadharFrontUrl: "",
  aadharBackUrl: "",
  isAvailable: true,
  hourlyRate: 800,
  primaryCar: {
    vehicleModel: "Innova Crysta",
    vehiclePlate: "UP 65 AB 4321",
    carBrand: "Toyota",
    vehicleType: "suv",
    vehicleCapacity: 6,
    fuelType: "diesel",
    isAc: true,
    luggageCapacityBags: 4,
    isPetFriendly: false,
    smokingAllowed: false,
    cabPhoto: "",
  },
};

export const mockTours: Tour[] = [
  {
    id: "tour_001",
    driverId: "drv_001",
    name: "Agra | Ramesh Gupta | 4.90 | Innova Crysta | 6 | Diesel",
    city: "Agra", state: "Uttar Pradesh", country: "India",
    category: "heritage",
    description: "Start the day with the iconic Taj Mahal at sunrise before the crowds arrive. After sunrise, explore the magnificent Agra Fort and its Mughal architecture. Includes expert commentary at every stop.",
    stops: [
      { id: "s1", name: "Taj Mahal (East Gate)", description: "Sunrise entry — golden hour photography", durationMinutes: 90, order: 1 },
      { id: "s2", name: "Mehtab Bagh", description: "Sunset garden with rear Taj view", durationMinutes: 30, order: 2 },
      { id: "s3", name: "Agra Fort", description: "UNESCO World Heritage fortress", durationMinutes: 75, order: 3 },
      { id: "s4", name: "Kinari Bazaar", description: "Local market for souvenirs", durationMinutes: 45, order: 4 },
    ],
    schedule: { startTime: "06:00", endTime: "18:00", daysOfWeek: [0, 2, 4, 6] },
    pricePerPerson: 1200,
    currency: "₹",
    maxGuests: 6,
    currentBookings: 4,
    status: "published",
    createdAt: "2026-01-10T08:00:00",
    estimatedDurationMinutes: 240,
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: "tour_002",
    driverId: "drv_001",
    name: "Mathura | Ramesh Gupta | 4.90 | Innova Crysta | 6 | Diesel",
    city: "Mathura", state: "Uttar Pradesh", country: "India",
    category: "religious",
    description: "Visit the birthplace of Lord Krishna in Mathura and explore the sacred temples of Vrindavan. Perfect for those seeking a spiritual and culturally rich experience.",
    stops: [
      { id: "s5", name: "Krishna Janmabhoomi", description: "Birthplace of Lord Krishna", durationMinutes: 60, order: 1 },
      { id: "s6", name: "Dwarkadhish Temple", description: "Magnificent 19th-century temple", durationMinutes: 45, order: 2 },
      { id: "s7", name: "Banke Bihari Temple, Vrindavan", description: "One of the most famous temples", durationMinutes: 45, order: 3 },
      { id: "s8", name: "ISKCON Vrindavan", description: "Grand spiritual complex", durationMinutes: 45, order: 4 },
      { id: "s9", name: "Prem Mandir", description: "Stunning marble temple lit at night", durationMinutes: 45, order: 5 },
    ],
    schedule: { startTime: "07:00", endTime: "18:00", daysOfWeek: [1, 3, 5] },
    pricePerPerson: 900,
    currency: "₹",
    maxGuests: 6,
    currentBookings: 2,
    status: "published",
    createdAt: "2026-02-05T10:00:00",
    estimatedDurationMinutes: 300,
    rating: 4.8,
    reviewCount: 54,
  },
  {
    id: "tour_003",
    driverId: "drv_001",
    name: "Fatehpur Sikri | Ramesh Gupta | 4.90 | Innova Crysta | 6 | Diesel",
    city: "Fatehpur Sikri", state: "Uttar Pradesh", country: "India",
    category: "heritage",
    description: "Explore the abandoned Mughal capital of Fatehpur Sikri, a UNESCO World Heritage Site just 40km from Agra. A lesser-known gem with stunning architecture.",
    stops: [
      { id: "s10", name: "Buland Darwaza", description: "Gateway of Magnificence — 54m high", durationMinutes: 30, order: 1 },
      { id: "s11", name: "Jama Masjid", description: "The grand mosque within the complex", durationMinutes: 30, order: 2 },
      { id: "s12", name: "Panch Mahal", description: "5-storey pavilion with 176 columns", durationMinutes: 45, order: 3 },
      { id: "s13", name: "Diwan-i-Khas", description: "Hall of Private Audience", durationMinutes: 30, order: 4 },
    ],
    schedule: { startTime: "09:00", endTime: "18:00", daysOfWeek: [2, 5, 6] },
    pricePerPerson: 750,
    currency: "₹",
    maxGuests: 6,
    currentBookings: 0,
    status: "draft",
    createdAt: "2026-06-20T12:00:00",
    estimatedDurationMinutes: 210,
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk_001",
    tourId: "tour_001",
    tourName: "Taj Mahal Sunrise & Agra Fort",
    tourDate: "2026-06-29",
    guest: { id: "g1", name: "Sarah Johnson", phone: "+1-555-0101", guestCount: 2, specialRequests: "Vegetarian lunch please" },
    status: "confirmed",
    totalAmount: 2400,
    currency: "₹",
    bookedAt: "2026-06-25T14:30:00",
  },
  {
    id: "bk_002",
    tourId: "tour_001",
    tourName: "Taj Mahal Sunrise & Agra Fort",
    tourDate: "2026-06-29",
    guest: { id: "g2", name: "Marco Rossi", phone: "+39-333-1234567", guestCount: 2 },
    status: "confirmed",
    totalAmount: 2400,
    currency: "₹",
    bookedAt: "2026-06-26T09:15:00",
  },
  {
    id: "bk_003",
    tourId: "tour_002",
    tourName: "Mathura & Vrindavan Spiritual Journey",
    tourDate: "2026-06-30",
    guest: { id: "g3", name: "Priya & Arun Mehta", phone: "+91-98765-43210", guestCount: 2, specialRequests: "Early morning puja if possible" },
    status: "pending",
    totalAmount: 1800,
    currency: "₹",
    bookedAt: "2026-06-28T07:00:00",
  },
  {
    id: "bk_004",
    tourId: "tour_001",
    tourName: "Taj Mahal Sunrise & Agra Fort",
    tourDate: "2026-07-02",
    guest: { id: "g4", name: "Yuki Tanaka", phone: "+81-90-1234-5678", guestCount: 3 },
    status: "pending",
    totalAmount: 3600,
    currency: "₹",
    bookedAt: "2026-06-28T10:45:00",
  },
  {
    id: "bk_005",
    tourId: "tour_002",
    tourName: "Mathura & Vrindavan Spiritual Journey",
    tourDate: "2026-06-27",
    guest: { id: "g5", name: "Ravi Sharma", phone: "+91-99887-76655", guestCount: 4 },
    status: "confirmed",
    totalAmount: 3600,
    currency: "₹",
    bookedAt: "2026-06-22T16:00:00",
  },
];

export const mockEarnings: TourEarning[] = [
  { tourId: "tour_001", tourName: "Taj Mahal Sunrise & Agra Fort", toursRun: 18, totalGuests: 72, grossRevenue: 86400, platformFee: 8640, netRevenue: 77760, currency: "₹" },
  { tourId: "tour_002", tourName: "Mathura & Vrindavan Spiritual Journey", toursRun: 12, totalGuests: 38, grossRevenue: 34200, platformFee: 3420, netRevenue: 30780, currency: "₹" },
];

export const mockPayout: PayoutSummary = {
  pendingPayout: 14400,
  lastPayoutAmount: 52800,
  lastPayoutDate: "2026-06-15",
  bankLast4: "4321",
  currency: "₹",
};
